apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfemily-db-pvc
  namespace: tfemily
  labels:
    app: tfemily-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfemily-db-deployment
  namespace: tfemily
  labels:
    app: tfemily-db
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfemily-db
  strategy: {}
  template:
    metadata:
      labels:
        app: tfemily-db
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          envFrom:
            - secretRef:
              name: tfemily-db-secret
          volumeMounts:
            - name: db-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: tfemily-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfemily-web-deploy
  namespace: tfemily
  labels:
    app: tfemily-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfemily-web
  strategy: {}
  template:
    metadata:
      labels:
        app: tfemily-web
    spec:
      containers:
      - image: tfes8/tfemily-web:latest
        name: tfemily-web
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: ALLOWED_ORIGINS
          value: "https://tfemily.com"
        - name: SPRING_OPTS
          value: "--spring.profiles.active=--spring.profiles.active=jpa-prod,db-docker-mysql,twitter,aws-local --spring.messages.basename=file:/messages,messages --server.port=8080 --spring.jpa.hibernate.ddl-auto=create-drop"
        - name: PHOTO_DIRECTORY
          value: "/photos/"
        - name: TWITTER_CONSUMER_KEY
          value: "BRhRexBkiwsOFRGi5oNAMFB9O"
        - name: TWITTER_CONSUMER_SECRET
          value: "K0S9PGoynsDjIDWlUEidsiCsLWN6MFOR4vzkDKsdWGNxLaTkQF"
        - name: MYSQL_DB_HOST
          value: "tfemily-web-svc"
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef: 
              key: MYSQL_DATABASE
              name: tfemily-db-secret
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef: 
              key: MYSQL_USER
              name: tfemily-db-secret
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef: 
              key: MYSQL_PASSWORD
              name: tfemily-db-secret
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tfemily-web-svc
  namespace: tfemily
  labels:
    app: tfemily-web
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tfemily-web
---
apiVersion: v1
kind: Service
metadata:
  name: tfemily-db-svc
  namespace: tfemily
  labels:
    app: tfemily-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: tfemily-db
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tfemily-web-ingress
  namespace: tfemily
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
spec:
  tls:
  - hosts:
    - tfemily.com
    secretName: tfemily-web-tls
  rules:
  - host: tfemily.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tfemily-web-svc
          servicePort: 8080

