name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag tfes8/tfemily-web:latest
        docker tag tfes8/tfemily-web:latest tfes8/tfemily-web:$(date +%s)
      
    - name: Log in to Docker Hub registry
      run: echo '${{ secrets.DOCKER_HUB_TOKEN }}' | docker login --username  ${{ secrets.DOCKER_USER_NAME }} --password-stdin
      
    - name: Push to Docker Hub
      run: docker push -a tfes8/tfemily-web
